### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [Pabmoy25/proyectoHotel-FrontEnd#95]
## Proceso

1. Ingrese a la pagina.
2. Navegue por la seccion "Nosotros".

## Resultado esperado

• Que los botones de las card redirijan a dicho sitio o una page 404.

## Resultado actual

• Los botones no cumplen ninguna funcion.

## Captura

![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/879367ca-d946-4bc5-b38b-fa639b91eb59)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Pabmoy25** [comment]
Buenas Nico
Muchas gracias por tus comentarios y sugerencias. Se realizaron las correcciones, en los botones de redes sociales, según lo indicado para su revisión.
