### ISSUE TITLE
Form reservas

### ISSUE THREAD

**Issue by NicoGonzalez94** [Pabmoy25/proyectoHotel-FrontEnd#96]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una reserva.

## Resultado esperado

• Que no se permitan colocar numeros ni signos en el nombre y apellido.
• Que al finalizar la reserva no se muestre informacion por consola.

## Resultado actual

•Se permite colocar numero y signos en el nombre y apellido.
• Al finalizar la reserva se muestra informacion por consola.

## Captura

![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/5c7579bf-9d6a-4e1d-876d-7b71c8f6bc7f)
![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/0ace0458-6768-4632-986a-c2408caf3c1c)
![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/f5156274-cd7b-4ccd-a118-d3913f07ebb6)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Pabmoy25** [comment]
Buenas Nico
Muchas gracias por tus comentarios y sugerencias. Se realizaron las correcciones según lo indicado para su revisión.
