### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [Pabmoy25/proyectoHotel-FrontEnd#97]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre del usuario.

## Resultado actual

• Se permite colocar numeros y signos en el nombre del usuario.

## Captura

![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/4f2fdfc9-83cb-443b-830b-4c85cef0244e)
![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/3d134019-5540-48ce-810a-67ca099f665f)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Pabmoy25** [comment]
Buenas Nico
Muchas gracias por tus comentarios y sugerencias. Se realizaron las correcciones según lo indicado para su revisión.
