### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by NicoGonzalez94** [Pabmoy25/proyectoHotel-FrontEnd#98]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un usuario nuevo.

## Resultado esperado

• Que no me permita colocar numeros ni signos en el nombre y apellido del usuario.
• Que al momento de registrarme no se muestre info por consola. 

## Resultado actual

• Se permite colocar numeros y signos en el nombre y apellido en el nombre del usuario.
• Se muestre info por consola que no se deberia de ver.

## Captura

![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/c962c5a8-211b-45df-929f-9e50e3005632)
![image](https://github.com/Pabmoy25/proyectoHotel-FrontEnd/assets/166792979/f4181722-392a-45b5-8a9b-79a0c4050b37)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Pabmoy25** [comment]
Buenas Nico
Muchas gracias por tus comentarios y sugerencias. Se realizaron las correcciones según lo indicado para su revisión.
